[package]
name = "solitaire"
version = "0.1.0"
authors = ["Martin Billinger <flkazemakase@gmail.com>"]


[dependencies.ggez]
version = "0.4"
features = ["cargo-resource-root"]

[dependencies]
rand = "*"