[package]
name = "solitaire"
version = "0.2.0"
authors = ["Martin Billinger <flkazemakase@gmail.com>"]

[features]
default = []
profiling = ["cpuprofiler"]


[dependencies.ggez]
version = "0.4"
features = ["cargo-resource-root"]

[dependencies]
cpuprofiler = { version = "0.0.3", optional = true }
env_logger = "*"
log = "*"
rand = "*"
sdl2 = "*"
